name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  qodana:
    runs-on: ubuntu-latest
    # 보안 강화를 위해 최소한의 권한을 부여합니다 (Least Privilege).
    permissions:
      contents: read          # 저장소 코드를 checkout 하기 위한 권한
      pull-requests: write    # PR에 Qodana 리포트를 코멘트로 게시하기 위한 권한
      security-events: write  # 결과를 GitHub Code Scanning에 업로드하기 위한 권한
    steps:
      - uses: actions/checkout@v4
        with:
          # ref를 명시하지 않으면 push 및 pull_request 이벤트 모두에서 올바른 커밋을 자동으로 checkout합니다.
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1 # 안정적인 최신 릴리스 버전을 사용합니다.
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          # --baseline 인수는 코드 품질 기준선을 설정하여 새로운 문제만 보고하도록 합니다.
          args: --baseline,qodana.sarif.json